SpigotPlus:
  Misc-Features: false
  World-Manager: false
  Inventory-Manager: false
  Gamemode-Manager: false
  MiscFeatures: {}
  WorldManager:
    worlds:
    - world
    - world_nether
    - world_the_end
    autoLoadWorlds: false
  InventoryManager:
    groups:
      AnyName:
      - someWorld
      World:
      - world
      - world_nether
      - world_the_end
  GamemodeManager:
    gamemode:
      CREATIVE: []
      SURVIVAL:
      - world
      - world_nether
      - world_the_end
      ADVENTURE: []
      SPECTATOR: []
