name: Multiworld
main: io.github.robotman3000.bukkit.multiworld.MultiWorld
version: 0.1.5-SNAPSHOT
commands:
   createworld:
      description: Creates a world or loads the world if it already exists.
      usage: /<command> <World Name> <seed> <world type> <world environment> <generate structures>
      permission: multiworld.create
      permission-message: You don't have <permission>
   generateworld:
      description: Generate a world.
      usage: /<command> <World Name> <generator:options>
      permission: multiworld.generate
      permission-message: You don't have <permission>
   deleteworld:
      description: Delete a world and all of its data.
      usage: /<command> <World Name>
      permission: multiworld.delete
      permission-message: You don't have <permission>
   unloadworld:
      description: Unload a world.
      usage: /<command> <World Name>
      permission: multiworld.unload
      permission-message: You don't have <permission>
   worldinfo:
      description: This allows you to get info for a world.
      usage: /<command> [World Name]
      permission: multiworld.info
      permission-message: You don't have <permission>
   listworlds:
      description: Lists all loaded worlds on the server.
      usage: /<command>
      permission: multiworld.list
      permission-message: You don't have <permission>
   gamerule:
      description: This allows you get and set gamerules.
      usage: /<command> [World Name] <gamerule> [new value]
      permission: multiworld.gamerule
      permission-message: You don't have <permission>
   worldproperty:
      description: Get and set the properties of a world.
      usage: /<command> [World Name] <property> [new value]
      permission: multiworld.property
      permission-message: You don't have <permission>
   goto:
      description: Teleport to a world.
      usage: /<command> <world> [player]
      permission: multiworld.teleport
      permission-message: You don't have <permission>
   inlist:
      description: Debugging Command to list all inventories on the server
      usage: /<command>
      permission: multiworld.inventory.list
      permission-message: You don't have <permission>